### ISSUE TITLE
Pretty quick Network indentation issue

### ISSUE THREAD

**Issue by mpavlak2018** [pingryiRT/P2P-Platform#12]
Traceback (most recent call last):
  File "Main.py", line 3, in <module>
    from Interface import Interface
  File "/Users/MitchellPavlak/Desktop/iRT/ChatInterface/ChatInterface2/ChatInterface/Interface.py", line 1, in <module>
    from P2PPlatform import Network
  File "/Users/MitchellPavlak/PythonProjects/P2PPlatform/__init__.py", line 1, in <module>
    from Network import Network
  File "/Users/MitchellPavlak/PythonProjects/P2PPlatform/Network.py", line 70
    finally:

IndentationError: expected an indented block

**Comment by jorndorff** [comment]
Just to clarify, this issue is filed against master right?

I believe this is fixed in MessageClass branch. I'm hoping we can work side-by-side sometime soonish to get this banged out. Then Message Class can be merged back in with master.
