### ISSUE TITLE
Missing alerters

### ISSUE THREAD

**Issue by mpavlak2018** [pingryiRT/P2P-Platform#6]
```Traceback (most recent call last):
  File "Main.py", line 29, in <module>
    myInterface.run()
  File "/Users/MitchellPavlak/Desktop/iRT/ChatInterface/ChatInterface2/ChatInterface/Interface.py", line 22, in run
    self.connector()
  File "/Users/MitchellPavlak/Desktop/iRT/ChatInterface/ChatInterface2/ChatInterface/Interface.py", line 108, in connector
    self.network.connect(peerIP, peerPort)
  File "/Users/MitchellPavlak/PythonProjects/P2PPlatform/Network.py", line 82, in connect
    self.alertOrStore(str(newPeer) + " connected.")
  File "/Users/MitchellPavlak/PythonProjects/P2PPlatform/Network.py", line 48, in alertOrStore
    if self.alerter is None:
AttributeError: 'Network' object has no attribute 'alerter'```

**Comment by jorndorff** [comment]
Latest commit makes progress on this (mostly by commenting out all the calls to alertOrStore). We're probably not done, but I think it is progress.
